### ISSUE TITLE
Read the Docs Error

### ISSUE THREAD

**Issue by josesanchez1815** [josesanchez1815/sphinx-vidlet-hosting#1]
@ACharbonneau 
@ctb
Any thoughts on these errors
Running Sphinx v1.8.5
loading translations [en]... done
making output directory...
building [mo]: targets for 0 po files that are out of date
building [readthedocs]: targets for 1 source files that are out of date
updating environment: 1 added, 0 changed, 0 removed
reading sources... [100%] index

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/sphinx-vidlet-hosting/envs/latest/lib/python3.7/site-packages/sphinx/cmd/build.py", line 304, in build_main
    app.build(args.force_all, filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/sphinx-vidlet-hosting/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 341, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/sphinx-vidlet-hosting/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 347, in build_update
    len(to_build))
  File "/home/docs/checkouts/readthedocs.org/user_builds/sphinx-vidlet-hosting/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 360, in build
    updated_docnames = set(self.read())
  File "/home/docs/checkouts/readthedocs.org/user_builds/sphinx-vidlet-hosting/envs/latest/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 472, in read
    self.env.doc2path(self.config.master_doc))
sphinx.errors.SphinxError: master file /home/docs/checkouts/readthedocs.org/user_builds/sphinx-vidlet-hosting/checkouts/latest/docs/source/contents.rst not found

Sphinx error:
master file /home/docs/checkouts/readthedocs.org/user_builds/sphinx-vidlet-hosting/checkouts/latest/docs/source/contents.rst not found

**Comment by ACharbonneau** [comment]
RTD is always going to be more finicky than your local renderer. I think your error here is that you haven't told it where your master file is. It is looking for something called `contents.rst` but you don't have one. You just need to tell it that yours is called index. Add:

> master_doc = 'index'

into your conf.py

**Comment by ACharbonneau** [comment]
local renderers are often nicer and will just look for all the reasonable options before breaking. RTD is...picky.

**Comment by ctb** [comment]
(this can also occurr if you fail to add all files to github)

**Comment by josesanchez1815** [comment]
https://sphinx-vidlet-hosting.readthedocs.io/en/latest/
Problem Resolved it turned out I needed to include 
master_doc = 'index' in the conf.py
Thank you both!
